# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "hit_counter"
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Roderick Monje"]
  s.date = "2011-09-18"
  s.email = "rod@seologic.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "hit_counter.gemspec",
    "lib/hit_counter.rb",
    "public/images/digits/celtic/0.gif",
    "public/images/digits/celtic/1.gif",
    "public/images/digits/celtic/2.gif",
    "public/images/digits/celtic/3.gif",
    "public/images/digits/celtic/4.gif",
    "public/images/digits/celtic/5.gif",
    "public/images/digits/celtic/6.gif",
    "public/images/digits/celtic/7.gif",
    "public/images/digits/celtic/8.gif",
    "public/images/digits/celtic/9.gif",
    "public/images/digits/odometer/0.gif",
    "public/images/digits/odometer/1.gif",
    "public/images/digits/odometer/2.gif",
    "public/images/digits/odometer/3.gif",
    "public/images/digits/odometer/4.gif",
    "public/images/digits/odometer/5.gif",
    "public/images/digits/odometer/6.gif",
    "public/images/digits/odometer/7.gif",
    "public/images/digits/odometer/8.gif",
    "public/images/digits/odometer/9.gif",
    "public/images/digits/scout/0.gif",
    "public/images/digits/scout/1.gif",
    "public/images/digits/scout/2.gif",
    "public/images/digits/scout/3.gif",
    "public/images/digits/scout/4.gif",
    "public/images/digits/scout/5.gif",
    "public/images/digits/scout/6.gif",
    "public/images/digits/scout/7.gif",
    "public/images/digits/scout/8.gif",
    "public/images/digits/scout/9.gif",
    "spec/lib/hit_counter_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/ivanoblomov/hit_counter"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Ruby version of that old 90s chestnut, the web-site hit counter."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<addressable>, [">= 0"])
      s.add_runtime_dependency(%q<mongoid>, [">= 0"])
      s.add_runtime_dependency(%q<rmagick>, ["= 2.12.2"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<addressable>, [">= 0"])
      s.add_dependency(%q<mongoid>, [">= 0"])
      s.add_dependency(%q<rmagick>, ["= 2.12.2"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<addressable>, [">= 0"])
    s.add_dependency(%q<mongoid>, [">= 0"])
    s.add_dependency(%q<rmagick>, ["= 2.12.2"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

