name: Release
on:
  push:
    tags:
      - '*'
permissions: read-all
jobs:
  push:
    name: Push gem to RubyGems.org
    runs-on: ubuntu-latest

    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
      contents: write # IMPORTANT: this permission is required for `rake release` to push the release tag

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          fetch-depth: 0
          ref: master
          persist-credentials: true
      - run: |
          sudo apt-get update
          sudo apt-get install -y libmagickwand-dev
      - uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f
        with:
          bundler-cache: true
          ruby-version: ruby
      - uses: rubygems/release-gem@6317d8d1f7e28c24d28f6eff169ea854948bd9f7
