name: Release
on:
  push:
    tags:
      - '*'
permissions: read-all
jobs:
  push:
    name: Push gem to RubyGems.org
    runs-on: ubuntu-latest

    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
      contents: write # IMPORTANT: this permission is required for `rake release` to push the release tag

    steps:
      - uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0
          ref: master
          persist-credentials: true
      - run: |
          sudo apt-get update
          sudo apt-get install -y libmagickwand-dev
      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b
        with:
          bundler-cache: false
          ruby-version: ruby
      - uses: rubygems/release-gem@7f9650160c1a4e7989fdc9855807bdbd421d8b6b
