name: Test
on:
  push:
permissions:
  contents: read
  id-token: write
jobs:
  test:
    environment: staging
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby-version }}
    strategy:
      matrix:
        ruby-version: [3.3, 3.4, 4.0]
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
      with:
        egress-policy: audit

    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
    - uses: supercharge/mongodb-github-action@315db7fe45ac2880b7758f1933e6e5d59afd5e94
      with:
        mongodb-version: '4.4'
    - run: |
        sudo apt-get update
        sudo apt-get install -y libmagickwand-dev
    - uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # 'bundle install' and cache
    - run: bundle exec rake
    - run: bundle exec rubocop
    - run: bundle exec inch --pedantic
    - uses: qltysh/qlty-action/coverage@fd52dc852530a708d68c3b7342f8d33d1df4cd55 # v2.2.1
      with:
        codeclimate-test-reporter-id: ${{ secrets.CC_TEST_REPORTER_ID }}
        oidc: true
        files: coverage/lcov.info
    - uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
